banana.data = read.csv("banana.csv", header = TRUE)
attach(banana.data)
summary(Size)
summary(Weight)
summary(Sweetness)
summary(Softness)
summary(Ripeness)
summary(Acidity)
summary(HarvestTime)
par(mfrow=c(2,3))
qqnorm(banana.data$Sweetness, main="Sweetness QQ Plot")
qqline(banana.data$Sweetness, col="red")
qqnorm(banana.data$Softness, main="Softness QQ Plot")
qqline(banana.data$Softness, col="red")
qqnorm(banana.data$Ripeness, main="Ripeness QQ Plot")
qqline(banana.data$Ripeness, col="red")
qqnorm(banana.data$Acidity, main="Acidity QQ Plot")
qqline(banana.data$Acidity, col="red")
qqnorm(banana.data$Size, main="Size QQ Plot")
qqline(banana.data$Size, col="red") 
qqnorm(banana.data$Weight, main="Weight QQ Plot")
qqline(banana.data$Weight, col="red")
c = data.frame(Size, Weight, Sweetness, Softness,Ripeness, Acidity)
pairs(c)
good = subset(banana.data,Quality == "Good")
hist(good$HarvestTime,main="Harvest Time of Good Bananas",xlab ="Harvest Time" )
bad = subset(banana.data,Quality == "Bad")
hist(bad$HarvestTime,main="Harvest Time of Bad Bananas",xlab ="Harvest Time" )
par(mfrow=c(2,3))
boxplot(Size~Quality,data = banana.data)
boxplot(Weight~Quality,data = banana.data)
boxplot(Sweetness~Quality,data = banana.data)
boxplot(Softness~Quality,data = banana.data)
boxplot(Ripeness~Quality,data = banana.data)
boxplot(Acidity~Quality,data = banana.data)
x = subset(banana.data,Quality == "Good" & Ripeness >= 0.7811)



